# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('tenants', '0002_tenant_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('ready', 'Ready'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                            ('expired', 'Expired'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'cart',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='checkout_sessions',
                        to='cart.cart',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='tenants.tenant',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='checkout_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(
                fields=['tenant', 'status'],
                name='checkout_ch_tenant__83b44b_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(
                fields=['user', 'status'],
                name='checkout_ch_user_id_6e9990_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(
                fields=['cart', 'status'],
                name='checkout_ch_cart_id_3ba797_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(
                fields=['idempotency_key'],
                name='checkout_ch_idempot_de8bc9_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'idempotency_key'),
                name='unique_checkout_session_idempotency_per_tenant',
            ),
        ),
    ]
