# Generated by Django 6.0.4 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField()),
                (
                    'response_time_ms',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    'tenant_id',
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['created_at'],
                        name='request_log_created_9c6773_idx',
                    ),
                    models.Index(
                        fields=['status_code'],
                        name='request_log_status__6d0a00_idx',
                    ),
                ],
            },
        ),
    ]
