# Generated by Django 6.0.4 on 2026-05-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_country_of_origin_brand_logo'),
        ('tenants', '0002_tenant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('storage', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=100, verbose_name='RAM')),
                ('variant_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['product__name', 'color', 'storage', 'ram'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'color', 'storage', 'ram'), name='unique_product_variant_per_tenant')],
            },
        ),
    ]
