# Generated by Django 6.0.4 on 2026-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_mptt_category_tree_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='large',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/images/generated/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='medium',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/images/generated/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/images/generated/'),
        ),
    ]
