# Generated by Codex on 2026-05-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_description'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='vendor.vendorprofile',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['tenant', 'vendor'],
                name='catalog_pro_tenant__1395cc_idx',
            ),
        ),
    ]
