# Generated by Codex on 2026-05-24

from django.db import migrations


def backfill_product_vendors(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    Inventory = apps.get_model('inventory', 'Inventory')

    products = Product.objects.filter(vendor__isnull=True).only('id')
    for product in products.iterator():
        inventory = Inventory.objects.filter(
            product_variant__product_id=product.id,
        ).order_by('id').first()

        if inventory is None:
            continue

        Product.objects.filter(id=product.id).update(
            vendor_id=inventory.vendor_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_vendor'),
        ('inventory', '0002_align_inventory_with_vendor_dashboard'),
    ]

    operations = [
        migrations.RunPython(
            backfill_product_vendors,
            migrations.RunPython.noop,
        ),
    ]
