# Generated by Django 6.0.4 on 2026-05-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('nightly_sales', 'Nightly sales')], db_index=True, max_length=50)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['tenant', 'report_type', '-generated_at'], name='ai_aireport_tenant__da31bb_idx')],
            },
        ),
    ]
