# Generated by Codex on 2026-05-12

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('cart', '0001_initial'),
        ('tenants', '0002_tenant_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order_number',
                    models.CharField(
                        db_index=True,
                        default=orders.models.generate_order_number,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('confirmed', 'Confirmed'),
                            ('processing', 'Processing'),
                            ('shipped', 'Shipped'),
                            ('delivered', 'Delivered'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('shipping_address', models.JSONField(default=dict)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'checkout_session',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order',
                        to='checkout.checkoutsession',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='tenants.tenant',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='orders',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('product_name', models.CharField(max_length=255)),
                ('variant_label', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='orders.order',
                    ),
                ),
                (
                    'product_variant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_items',
                        to='catalog.productvariant',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_set',
                        to='tenants.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['tenant', 'status'],
                name='orders_orde_tenant__b18f3e_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['user', 'status'],
                name='orders_orde_user_id_75d6ea_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['order_number'],
                name='orders_orde_order_n_0fb8b4_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(
                fields=['tenant', 'order'],
                name='orders_orde_tenant__e8f030_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(
                fields=['tenant', 'product_variant'],
                name='orders_orde_tenant__5eb05b_idx',
            ),
        ),
    ]
